services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.11
    container_name: homepage
    ports:
      - 3000:3000
    env_file: .env # use .env
    volumes:
      - ./config:/app/config
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PUID: $PUID # read from .env
      PGID: $PGID # read from .env
      HOMEPAGE_ALLOWED_HOSTS: gondolin.robertharte.net,homepage.robertharte.net
    networks:
      - home_network

networks:
  home_network:
    name: home_network
    external: false