# Main context (this is the global configuration)
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include mime.types;

    # 
    upstream docker_containers {
        server homepage.robertharte.net:3000; # Homepage
        server pgadmin.robertharte.net:3001; # pgAdmin
    }

    server {
        listen 443 ssl;  # Listen on port 443 for HTTPS
        server_name localhost;

        # SSL certificate settings
        ssl_certificate /etc/nginx/nginx-certs/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/nginx-certs/nginx-selfsigned.key;

        # Proxying requests to docker containers
        location / {
            proxy_pass http://docker_containers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Optional server block for HTTP to HTTPS redirection
    server {
        listen 80;  # Listen on port 80 for HTTP
        server_name localhost;

        # Redirect all HTTP traffic to HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }
}