---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Monitoring:
    - Grafana:
        href: http://grafana.robertharte.net

- Database:
    - pgAdmin:
        href: https://pgadmin.robertharte.net
